### ISSUE TITLE
Touch Plus Controllers Quest 3

### ISSUE THREAD

**Issue by ramonmata** [truefranco/MetaXRv62#2]
Hello @truefranco, 

Wondering if you have tried to add the **touch plus** static mesh references in `OculusXRControllerComponent.cpp`, which already exist in the METAXR package.

Somehow the code says models are not available but they are included `MetaXR\Content\Meshes`

https://github.com/truefranco/MetaXRv65/blob/0ef5a1fa3493fa32f179e4b57f6926f0113dacb0/MetaXR/Source/OculusXRInput/Private/OculusXRControllerComponent.cpp#L129

Love to try myself but now sure how to setup the files in order to compile the plugin.

**Comment by truefranco** [comment]
Sorry I dont understand what the issue is. The code say that but the mesh as you say is there and it work.

**Comment by ramonmata** [comment]
Hi, never mind, I found the way to display the correct HMD controllers on Quest 3 by using the `XRDeviceVisualizationComponent` provided in Unreal Engine.

best regards,
Ramon
